repository: kaiminz/kaiminz.github.io
repository_url: https://github.com/kaiminz/kaiminz.github.io

timezone: Asia/Shanghai
lang: zh_CN

title: 北邮人导航 · BYR-Navi
alias_en: BYR-Navi
alias_cn: 北邮人导航
description: A Navigation Website for BYR
keywords: 北邮人导航, BYR-Navi, BYR, Navi, Navigation
url: https://kaiminz.github.io
established_at: "2021-08-31T00:00+08:00"

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net
contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
